### ISSUE TITLE
I got the error while running 

### ISSUE THREAD

**Issue by iloo123** [ionic-team/ionic-v1#306]
> `ionic cordova build android --prod --release`

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:18:20
    at Object.<anonymous> (C:\Users\Thailu\AppData\Roaming\npm\node_modules\ionic\node_modules\unzip\node_modules\fstream\node_modules\graceful-fs\fs.js:11:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

Cannot find module 'internal/fs' (CLI v2.0.0)

Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 1.3.3
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
OS:
Node Version: v7.10.0

**Comment by dhavalsoni2001** [comment]
I am facing same issue. Any solution?
