### ISSUE TITLE
unable to install ionic-v1

### ISSUE THREAD

**Issue by mccob** [ionic-team/ionic-v1#353]
```
$ sudo npm install -g ionic@1.3.5
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! code ETARGET
npm ERR! notarget No matching version found for i@0.3.2
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

log file : 

```
358 silly fetchPackageMetaData error for i@0.3.2 No matching version found for i@0.3.2
359 verbose type version
360 verbose stack i: No matching version found for i@0.3.2
360 verbose stack     at pickManifest (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/npm-pick-manifest/index.js:65:11)
360 verbose stack     at fetchPackument.then.packument (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:52:18)
360 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
360 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
360 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
360 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
360 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
360 verbose stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
360 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
360 verbose stack     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
360 verbose stack     at runCallback (timers.js:672:20)
360 verbose stack     at tryOnImmediate (timers.js:645:5)
360 verbose stack     at processImmediate [as _immediateCallback] (timers.js:617:5)
```

also seen here : https://forum.ionicframework.com/t/error-when-trying-npm-install-ionic-1-3-5/112892

**Comment by paredesivan** [comment]
npm install -g cordova 
npm install -g ionic

ambos como administrador

**Comment by meyyappanv** [comment]
@mccob By any chance were you able to get past this?

**Comment by pino** [comment]
Apparently this is because version 0.3.2 of inflect was unpublished. The developer recommended updating it to 0.3.3. See: [https://npmjs.com/package/i](https://npmjs.com/package/i) 

Might be solved by manually `npm install i@0.3.3`.
